### PR TITLE
Find adapter

### PR DESCRIPTION
**Pull request by Nitrokitty**
Continue searching for the adapter if the source is not an entity meta
**Important - Do not complete without reviewing the following PRs:**
- https://github.com/cognitoforms/model.js/pull/14
- https://cognitoforms.visualstudio.com/Cognito%20Forms/_git/Cognito%20Forms/pullrequest/2339

### CODE REVIEW

**Comment by tskimmett** [comment]
@Nitrokitty Can you provide some background on this? Is it fixing a bug?

**Comment by Nitrokitty** [comment]
@tskimmett Yes! When I added ValidatedPropertySource as a mixin to the date picker (in Date.vue) to access the range rule `this.$source.property.rules.find(r => r.name === 'Range')`, it incorrectly returned the parent as the c-date component instead of the form. Even though the c-date component is an adapter, it's not an entity. It really needed to return it's parent. I've since removed the mixin from datepicker, but it might be worth fixing for furture components!

**Comment by mattheyan** [comment]
@Nitrokitty The date component isn't really a source binding component, its a source-agnostic UI control, right? And the source path concept doesn't make sense unless you have a property to bind to. How were you trying to use it?

**Comment by Nitrokitty** [comment]
I was just trying to access the range rule for the old implementation. `this.$source.property.rules.find(r => r.name === 'Range')`. Accessing the source was the only example I could find that allowed acess to the rules. I appologize if I was using it wrong haha. I've changed the implementation so we can disregard this PR!

**Comment by mattheyan** [comment]
Getting access to the source is definitely something you should be able to do, as long as you're ok with the component being aware of "source" concepts. Instead of source path adapter, you'd have to use something else, something that would just get access to its parent source component. But, I don't think that exists yet. 😛

**Pull request closed without merging**
